add timestamp to ethr builder
xmtp/didethresolver pull request #48
Opened 2024-02-14 18:07 UTC by insipx

related to https://github.com/xmtp/xps-gateway/issues/61

timestamp is not the best way b/c we can have multiple installation id updates in the same block. It may be OK in the general case, since it could be rare that a user updates their installation key in the same block twice, but it can happen. libxmtp relies on it in order to sort through installation ids it already has. In the future it would be better to use a block # / log index combo. This would also avoid yet another api call to the ethereum rpc node

2024-02-14 18:28 UTC, 37ng approved these changes
LGTM!
Looks like we need a rustfmt.toml to unify `cargo fmt`

2024-02-14 18:42 UTC, insipx commented
> LGTM! Looks like we need a rustfmt.toml to unify `cargo fmt`

we should be just on the stable default rustfmt settings, in this case my lsp crashed and i didn't get the autoformatting I usually do

2024-02-14 19:58 UTC, jac18281828 requested changes
I think we should be consistent in our use of block timestamp in seconds

2024-02-14 19:58 UTC, jac18281828 commented on lib/src/resolver.rs
> +    pub timestamp: i64,
Block timestamp may be more relevant for future viewers of this code

2024-02-14 19:58 UTC, jac18281828 commented on lib/src/resolver.rs
> +        let timestamp = block
This should be consistent by fetching the block time from Ethereum or failing.   Block time can differ from real time.

2024-02-14 20:32 UTC, insipx commented
removed logic to convert to datetime b/c it was wasteful, changed to store the usual timestamp and then multiply for nanoseconds @jac18281828

2024-02-15 00:20 UTC, jac18281828 approved these changes
Looks good !  One last thing, I’d use Duration for time conversion.

2024-02-15 00:20 UTC, jac18281828 commented on lib/src/types/xmtp.rs
> +        let timestamp_ns = context.block_timestamp * NANOSECONDS_PER_SECOND;
https://doc.rust-lang.org/std/time/struct.Duration.html#method.as_nanos

2024-02-15 00:20 UTC, jac18281828 commented on lib/src/types/xmtp.rs
> +        let timestamp_ns = context.block_timestamp * NANOSECONDS_PER_SECOND;
Is use Duration for this

2024-02-15 23:28 UTC, merged